### ISSUE TITLE
Feature request: Adding 'sustainability' label at info under Site Health > Information tab

### ISSUE THREAD

**Issue by YellowlimeNL** [LittleBigThing/carbon-footprint#10]
As already applied to the Site Health's status tab.

**Comment by LittleBigThing** [comment]
I followed the WP standard and added a tab, similar to other tabs on that page. Other tabs do not have a label. Do you mean to change the title of the tab? It is currently called ‘Carbon Footprint’.

![Screenshot 2024-10-25 at 09 02 25-min](https://github.com/user-attachments/assets/1ea22f7b-54b5-4dfa-994f-975e390d160f)

**Comment by YellowlimeNL** [comment]
Ah I see, the WP standard is not having labels at this tab. Fair enough.

I'll close this issue then. Carbon Footprint seems the right description to me.
