### ISSUE TITLE
Add test date and time to test result

### ISSUE THREAD

**Issue by LittleBigThing** [LittleBigThing/carbon-footprint#2]
The plugin tests the carbon footprint of the homepage. The result is cached for 24h as a transient. Also, the API caches the result for 24h as well.

It is useful to see when the test was performed, so the time and the date of the test should be added. This helps the user understand why the results do not change even if they modify the homepage, for example. Maybe some additional explanation about the caching should be added as well?

**Comment by LittleBigThing** [comment]
PR #1 should do it

**Comment by LittleBigThing** [comment]
Example:

![Screenshot 2023-05-18 at 13 37 41](https://github.com/LittleBigThing/carbon-footprint/assets/5901923/45f2f92c-6a9a-4f37-80d6-6882865a738f)

**Comment by YellowlimeNL** [comment]
Works as a charm!

**Comment by LittleBigThing** [comment]
Added date and time of test in #1.
Might be interesting to add more information about how long the test result is cached later.
